[O2]
critical = 1.8
pure = 0.8
pure_vent_time = 0
pure_timeout = 1200

[Control1]
ip = 192.168.5.110
servo_n = 3
servo_ids = S1 S2 S3
dout = --- --- lock --- vent argon20 argon5 diffusor

[BP]
beam_player = firmware/2x_beam_player/2x_beam_player
version = 1

[LASER]
x0 = 0
y0 = 0
offset_x = -3.3000000000000007
offset_y = -7.3999999999999995
scale_x = 1.7750177335181268
scale_y = 1.786501939761514
jump_speed = 6000
decel_dist = .5
decel_speed = 850
angle_tolerance = 30
on_delay = -320000
chan1_x = 1
power = 300
analog_scale = 4

[SVG]
x0 = 0
y0 = 0
size = 150
zoom_factor = 70

[LAM]
layer_time = 7.7
loadlevel = 1.4
loadlevel_add = 15
powder_mul = 1.4
rk_feed = 1200
rk_rapid = 1500
photo_log_len = 10
language = ru.json
preview_template = inc/template.svg
powder_override = 128
type = mid

[Camera]
exposure = 200
brightness = 50
contrast = 50
saturation = 100
gain = 0.1
focus = 100
calibration0 = 975.05
calibration1 = 778.5
calibration2 = 235.85
calibration3 = 788.1
calibration4 = 319.05
calibration5 = 247.3
calibration6 = 927.05
calibration7 = 215.3
frame_width = 1280
frame_height = 960

[S1]
offset = 0
home = 6
min = 0
max = 275
middle = 118
pitch = 10

[S2]
offset = 0
home = 0
min = 0
max = 137.327
pitch = 5

[S3]
offset = 0
home = -15.620000000000001
min = -24
max = 117.143
pitch = 5

[Cluster]
upload_dir = uploads
logs_dir = logs
batch_size = 15
info_interval = 5
admin_commands = timer_start timer_stop timer_reset send_photo send_message register
general_commands = timer_stop send_photo send_message register

[ModbusUDP]
arduino_ip = 192.168.5.140
port_send_udp = 5276
port_listen_udp = 5277
device = nanoatmega328
; analog_pins = a2 a3 a4 a5
; a0 - t a1 - s
; 1: a2 - s, a4 - t | 2: a3 - s, a5 - t

pid_i_p = 0.3
pid_i_i = 0.0
pid_i_d = 0.2
pid_i_deadband = 1.5
rele_threshold = 0.05

cmd_read_sev = 0x03
cmd_write_one = 0x06

cmd_read_analog_pins = 170
cmd_read_temps = 120
cmd_read_freqs = 130
cmd_modbus_command = 140
cmd_read_thermo = 150
cmd_toggle_rele = 160
cmd_check_rele = 161

[ModbusUDP.Slave 2]
name = Gadget 2
slave_id = 0x02

analog_pin_signal = a0 
analog_pin_temp = a1
; s - 3, t - 5

register_address_read_1 = 0x0C81
register_address_read_2 = 0x0C82

register_address_write_1 = 0x2135
register_address_write_2 = 0x2136



; [ModbusUDP.Slave 3]
; name = Gadget 3
; slave_id = 0x03

; analog_pin_signal = a3
; analog_pin_temp = a4

; register_address_read_1 = 0x0C81
; register_address_read_2 = 0x0C82
; register_address_write_1 = 0x2135
; register_address_write_2 = 0x2136

; register_address_read_1 = 0x810C
; register_address_read_2 = 0x820C
; register_address_write_1 = 0x3521
; register_address_write_2 = 0x3621






